#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..')
const cardsPath = resolve(repoRoot, 'supabase/cards.json')
const seedPath = resolve(repoRoot, 'supabase/seed.sql')

const CEFR_LEVELS = new Set(['A1', 'A2', 'B1', 'B2', 'C1', 'C2'])
const REQUIRED_LANGUAGES = ['Dutch', 'Japanese']

function fail(message) {
  console.error(`generate-seed: ${message}`)
  process.exit(1)
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`
}

function validate(cards) {
  if (!Array.isArray(cards)) fail('cards.json must be a JSON array')
  const ids = new Set()
  cards.forEach((card, index) => {
    const where = `cards[${index}]`
    if (!card.id) fail(`${where}: missing id`)
    if (ids.has(card.id)) fail(`${where}: duplicate id ${card.id}`)
    ids.add(card.id)
    if (!card.question) fail(`${where} (${card.id}): missing question`)
    if (!CEFR_LEVELS.has(card.proficiency_level)) {
      fail(`${where} (${card.id}): proficiency_level must be one of ${[...CEFR_LEVELS].join(', ')}`)
    }
    if (!card.translations || typeof card.translations !== 'object') {
      fail(`${where} (${card.id}): missing translations object`)
    }
    for (const lang of REQUIRED_LANGUAGES) {
      if (!card.translations[lang]) {
        fail(`${where} (${card.id}): missing translations.${lang}`)
      }
    }
  })
}

function renderCardsInsert(cards) {
  const values = cards
    .map(
      (card) =>
        `    (${sqlString(card.id)}, ${sqlString(card.question)}, ${sqlString(card.proficiency_level)})`,
    )
    .join(',\n')
  return `INSERT INTO cards (id, question, proficiency_level) VALUES\n${values};`
}

function renderTranslationsInsert(cards, language) {
  const values = cards
    .map(
      (card) =>
        `    (${sqlString(card.id)}, ${sqlString(language)}, ${sqlString(card.translations[language])})`,
    )
    .join(',\n')
  return `INSERT INTO card_translations (card_id, language, translation) VALUES\n${values};`
}

function main() {
  const raw = readFileSync(cardsPath, 'utf8')
  const cards = JSON.parse(raw)
  validate(cards)

  const sections = [
    '-- GENERATED by scripts/generate-seed.js — do not edit by hand.',
    '-- Edit supabase/cards.json and re-run: node scripts/generate-seed.js',
    '',
    '-- Cards (questions are always in English)',
    renderCardsInsert(cards),
    '',
    '-- Card translations (Dutch)',
    renderTranslationsInsert(cards, 'Dutch'),
    '',
    '-- Card translations (Japanese)',
    renderTranslationsInsert(cards, 'Japanese'),
    '',
  ]

  writeFileSync(seedPath, sections.join('\n'))
  console.log(`generate-seed: wrote ${cards.length} cards to ${seedPath}`)
}

main()
